# This workflow will build a Java project with Maven, and cache/concurrencyore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build concurrency

on:
  push:
    paths:
      - "concurrency/**"
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  concurrency:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven
    - name: Start up Redis in Docker
      run: |
        docker compose up -d redis
        sleep 5
        docker ps -a    
    - name: Build with Maven
      run: |
        cd concurrency
        mvn -B -q clean verify -Parq-glassfish-managed
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: server-log
        path: concurrency/target/glassfish*/glassfish/domains/domain1/logs/server.log
              
